"""empty message

Revision ID: 369475a130cf
Revises: 9e7acb2d5574
Create Date: 2026-06-15 12:19:18.540100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '369475a130cf'
down_revision = '9e7acb2d5574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('UserVerificationCodes_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('UserVerificationCodes_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('used_at')

    # ### end Alembic commands ###
