"""empty message

Revision ID: 417192d7f360
Revises: 4a13d6ca47fd
Create Date: 2026-06-09 16:09:49.761219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417192d7f360'
down_revision = '4a13d6ca47fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provinces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_np', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_en'),
    sa.UniqueConstraint('name_np')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('provinces')
    # ### end Alembic commands ###
