"""empty message

Revision ID: 772a0f9a1744
Revises: 417192d7f360
Create Date: 2026-06-09 16:14:28.169869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '772a0f9a1744'
down_revision = '417192d7f360'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('districts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_np', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['provinces.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('province_id', 'name_en', name='_province_district_uc')
    )
    op.create_table('local_bodies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=False),
    sa.Column('name_en', sa.String(length=150), nullable=False),
    sa.Column('name_np', sa.String(length=150), nullable=False),
    sa.Column('body_type', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['districts.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('district_id', 'name_en', 'body_type', name='_district_local_body_uc')
    )
    op.create_table('local_body_wards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('local_body_id', sa.Integer(), nullable=False),
    sa.Column('ward_number', sa.Integer(), nullable=False),
    sa.CheckConstraint('ward_number > 0 AND ward_number <= 40', name='valid_ward_range'),
    sa.ForeignKeyConstraint(['local_body_id'], ['local_bodies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_body_id', 'ward_number', name='_local_body_ward_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('local_body_wards')
    op.drop_table('local_bodies')
    op.drop_table('districts')
    # ### end Alembic commands ###
