"""empty message

Revision ID: 9e7acb2d5574
Revises: 7cc5539d0ebd
Create Date: 2026-06-15 12:17:48.848355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7acb2d5574'
down_revision = '7cc5539d0ebd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('life_in_sec', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('UserVerificationCodes_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.drop_column('UserVerificationCodes_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('life_in_sec')

    # ### end Alembic commands ###
