"""empty message

Revision ID: d15140eff895
Revises: 369475a130cf
Create Date: 2026-06-15 12:22:11.531667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd15140eff895'
down_revision = '369475a130cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expired_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_verification_codes', schema=None) as batch_op:
        batch_op.drop_column('expired_at')

    # ### end Alembic commands ###
